### ISSUE TITLE
Can't run 'MiaSample' solution (Android part) in 'ReactNative' folder.

### ISSUE THREAD

**Issue by mindtheworld** [DIBS-Payment-Services/Easy-Android-SDK#15]
Feels like ReactNative solution is lacking the updates, having issues with react-native-rn-mia package. 
- 'author' inside package.json isn't defined correctly.  (missing 'id', 'name')
- Tried to following the step mentioned in README.md by ' `yarn add ./../react-native-rn-mia`, then run 'react-native run-android', got error in AndroidManifest.xml file.
- Tried to add the package from: https://www.npmjs.com/package/react-native-rn-mia (version 1.2.0), noticed method RNMia.checkoutWithPaymentID takes only 5 parameters instead of 6 (missing cancelUrl)

Could you pls update the RN sample solution? Thank you very much!

**Comment by mindtheworld** [comment]
Just tested the newly released version of react-native-rn-mia (1.6.0), still failed to build, have issues with package.json and RnMiaModule.java as showing below:

![image](https://user-images.githubusercontent.com/34175635/141092613-757c8bb6-dc08-42f0-9931-7d045f0e0e0d.png)

![image](https://user-images.githubusercontent.com/34175635/141092771-d83ab389-29cc-4362-b5e7-eb49c9da02a0.png)

eu.nets.mia.data.MiAPaymentInfo currently only takes 3 parameters, and there is no 'cancelUrl'. 

![image](https://user-images.githubusercontent.com/34175635/141093726-65e29be4-0f37-45f8-9ba7-f446d776bf2a.png)

I guess this is the reason: 
![image](https://user-images.githubusercontent.com/34175635/141133020-cf776349-a3cd-4454-b282-d8981f979b92.png)

**Comment by Nets-in-app** [comment]
Hi @mindtheworld ,

Thanks for your report! The MiASample is a reference implementation to show on how to integrate our RN MiA SDK and it is indeed not fully updated. Here are the quick suggestions to help you to run it properly from your end below.

Cancel url is newly added in release v1.3.0 https://github.com/Nets-eCom/Nets-Easy-Android-SDK/releases/tag/v1.3.0 which is not available at v1.1.0. You are right that you need to update the latest version from eu.nets.mia:mia-sdk:1.1.0 to eu.nets.mia:mia-sdk:1.6.0. In addition, Jcenter has been deprecated so that please add mavenCentral() as well under repositories section in build.gradle file in case you can download our mia sdk without any problem in the future.

In addition, those information in package.json file are populated with placeholders on purpose. Because we provide this example the RN bridge wrapper library in an open source manner so that you could fully reuse and modify in your own preference. You could replace your project information there instead.

Hope it makes sense for you! Let's know if you have any other questions!

**Comment by mindtheworld** [comment]
Hi @Nets-in-app 

Thanks for the clarification, and I'm now able to run MiaSample on both android and ios env.

One more question, is this npm package published by your team: https://www.npmjs.com/package/react-native-rn-mia ?

**Comment by Nets-in-app** [comment]
hi @mindtheworld 

Yes our team publishes the npm packlage **react-native-rn-mia**.

Thank you
BR

**Comment by mindtheworld** [comment]
Again, thank you for clarification:)
